@api = http://localhost:4000

GET {{api}}/noticias

###
GET {{api}}/noticias/6095eaec999fa12a742ad299

### Create news
POST {{api}}/noticias
Content-Type: application/json

{
    "url": "https://globoesporte.globo.com/rj/futebol/campeonato-carioca/noticia/finais-do-carioca-entre-flamengo-e-fluminense-serao-nos-proximos-dois-sabados-dias-14-e-21.ghtml",
    "title": "Flamengo",
    "description": "Final carioca"
}

###
DELETE {{api}}/noticias/6095e950b6d1860438b21ba9

###
PUT {{api}}/noticias/6095eaec999fa12a742ad299
Content-Type: application/json

{
    "title": "Contrato paris neste sabado"
}
